
# -----
# Build

Timezone: Etc/UTC

collections:
  musics:
    output: true
    permalink: /:path/

paginate: 10
permalink: pretty

defaults:
  - scope:
      path: ""
      type: musics
    values:
      layout: music-page

# ---
# Jekyll Config

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

sass:
  sass_dir: .
  style: compressed
